name: Cypress Tests

on: push

env:
  VITE_API_URL: http://localhost:3001
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build
      
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-folders
          path: |
            client/dist
            server/dist

  end-to-end-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
          path: .  # Corrigido: define o caminho raiz para extração
      
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:3000 http://localhost:3001/heroes'  # Corrigido: remover vírgula
          command: npm run test:e2e:ci
          record: true
          parallel: true
          group: 'E2E Tests'
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}

  component-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
          path: .  # Corrigido: define o caminho raiz para extração
      
      - name: Run CT Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:ct:ci
          record: true
          parallel: true
          group: 'Component Tests'
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}

  api-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
          path: .  # Corrigido: define o caminho raiz para extração
      
      - name: Run API Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:3000 http://localhost:3001/heroes'  # Corrigido: remover vírgula
          command: npm run test:api:ci
          record: true
          parallel: true
          group: 'API Tests'
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}
